package org.motechproject.nms.imi.domain;

public enum FileType {
    CDR_SUMMARY_FILE,
    CDR_DETAIL_FILE,
    WHATSAPP_CDR_DETAIL_FILE,
    TARGET_FILE,
    WHATSAPP_TARGET_FILE,
    WHATSAPP_SMS_TARGET_FILE,
    WHATSAPP_SMS_CDR_SUMMARY_FILE,
    WHATSAPP_CDR_SUMMARY_FILE,
}
