package org.motechproject.nms.kilkari.domain;

/**
 * Created by vishnu on 17/7/17.
 */
public enum RejectionReasons {
    FLW_TYPE_NOT_ASHA,
    INVALID_LOCATION,
    MOBILE_NUMBER_ALREADY_IN_USE,
    UPDATED_RECORD_ALREADY_EXISTS,
    FLW_IMPORT_ERROR,
    INVALID_LMP_DATE,
    ACTIVE_CHILD_PRESENT,
    INVALID_CASE_NO,
    ALREADY_LINKED_WITH_A_DIFFERENT_MOTHER_ID,
    INVALID_DOB,
    GF_STATUS_INACTIVE,
    MOBILE_NUMBER_ALREADY_SUBSCRIBED,
    ABORT_STILLBIRTH_DEATH,
    ALREADY_SUBSCRIBED,
    DUPLICATE_MOBILE_NUMBER_IN_DATASET,
    MOBILE_NUMBER_EMPTY_OR_WRONG_FORMAT,
    GF_STATUS_EMPTY_OR_WRONG_FORMAT,
    FIELD_NOT_PRESENT,
    DATA_INTEGRITY_ERROR,
    CHILD_DEATH
}
