package org.motechproject.nms.kilkari.domain;

/**
 * Created by vishnu on 17/7/17.
 */
public enum RejectionReasons {
    FLW_TYPE_NOT_ASHA,
    INVALID_LOCATION,
    MSISDN_ALREADY_IN_USE,
    RECORD_ALREADY_EXISTS,
    FLW_IMPORT_ERROR,
    INVALID_LMP_DATE,
    ACTIVE_CHILD_PRESENT,
    INVALID_CASE_NO,
    MOTHER_ID_ERROR,
    INVALID_DOB,
    GF_STATUS_INACTIVE,
    MSISDN_ALREADY_SUBSCRIBED,
    ABORT_STILLBIRTH_DEATH,
    ALREADY_SUBSCRIBED,
    DUPLICATE_MSISDN_IN_DATASET,
    NUMBER_FORMAT_ERROR,
    MSISDN_WITH_ONE_ACTIVE_SUBCRIPTION_PRESENT,
    MSISDN_EMPTY_OR_WRONG_FORMAT,
    GF_STATUS_EMPTY_OR_WRONG_FORMAT,
    FIELD_NOT_PRESENT
}
