package org.motechproject.nms.region.domain;

public enum LocationRejectionReasons {
    PARENT_LOCATION_ID_NOT_PRESENT_IN_FILE,
    PARENT_LOCATION_NOT_PRESENT_IN_DB,
    LOCATION_CODE_NOT_PRESENT_IN_FILE,
    LOCATION_NAME_NOT_PRESENT_IN_FILE,
    LOCATION_CODE_ZERO_IN_FILE,
    PARENT_TALUKA_AND_HEALTH_BLOCK_NOT_IN_SAME_DISTRICT,
    TALUKA_ID_NOT_PRESENT_IN_FILE,
    TALUKA_ID_NOT_PRESENT_IN_DB,
    NULL_MDDS_CODE
}
