package org.motechproject.nms.rejectionhandler.service;

import org.motechproject.nms.rejectionhandler.domain.VillageHealthSubFacilityImportRejection;

public interface VillageHealthSubFacilityRejectionService {
    void saveRejectedVillageHealthSubFacility(VillageHealthSubFacilityImportRejection villageHealthSubFacilityImportRejection);
}
